version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: echo "export BAZ=baz.`git log --pretty=format:%s -n 1 $CIRCLE_SHA1`" >> $BASH_ENV
      - run: echo "$BAZ"
      - run: echo 'export COMMIT_TAG=$(git log --pretty=format:%s -n 1 $CIRCLE_SHA1)' >> ~/.bashrc
      - run: echo $COMMIT_TAG
      - run: echo "$VARIABLE"
      - run: 'sudo pip install -r requirements.txt'
      ##- run: 'python main.py'
      - run: 'sudo zip -r images.zip images'
      - store_artifacts:
          path: images.zip
          prefix: images
workflows:
  version: 2
  build:
    jobs:
      - build